// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module InclusiveCacheControl(
  input         clock,
                reset,
  output        auto_ctrl_in_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_ctrl_in_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [2:0]  auto_ctrl_in_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_ctrl_in_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [1:0]  auto_ctrl_in_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [8:0]  auto_ctrl_in_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [25:0] auto_ctrl_in_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [7:0]  auto_ctrl_in_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input  [63:0] auto_ctrl_in_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         auto_ctrl_in_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:367:18
                auto_ctrl_in_d_ready,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output        auto_ctrl_in_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [2:0]  auto_ctrl_in_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [1:0]  auto_ctrl_in_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [8:0]  auto_ctrl_in_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  output [63:0] auto_ctrl_in_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:367:18
  input         io_flush_match,	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:39:16
                io_flush_req_ready,	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:39:16
  output        io_flush_req_valid,	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:39:16
  output [63:0] io_flush_req_bits,	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:39:16
  input         io_flush_resp	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:39:16
);

  wire [8:0]       out_bits_extra_tlrr_extra_source;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [1:0]       out_bits_extra_tlrr_extra_size;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [8:0]       in_bits_index;	// src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire             in_bits_read;	// src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire             _out_back_q_io_deq_valid;	// src/main/scala/chisel3/util/Decoupled.scala:376:21
  wire             _out_back_q_io_deq_bits_read;	// src/main/scala/chisel3/util/Decoupled.scala:376:21
  wire [8:0]       _out_back_q_io_deq_bits_index;	// src/main/scala/chisel3/util/Decoupled.scala:376:21
  wire [7:0]       _out_back_q_io_deq_bits_mask;	// src/main/scala/chisel3/util/Decoupled.scala:376:21
  wire             auto_ctrl_in_a_valid_0 = auto_ctrl_in_a_valid;
  wire [2:0]       auto_ctrl_in_a_bits_opcode_0 = auto_ctrl_in_a_bits_opcode;
  wire [2:0]       auto_ctrl_in_a_bits_param_0 = auto_ctrl_in_a_bits_param;
  wire [1:0]       auto_ctrl_in_a_bits_size_0 = auto_ctrl_in_a_bits_size;
  wire [8:0]       auto_ctrl_in_a_bits_source_0 = auto_ctrl_in_a_bits_source;
  wire [25:0]      auto_ctrl_in_a_bits_address_0 = auto_ctrl_in_a_bits_address;
  wire [7:0]       auto_ctrl_in_a_bits_mask_0 = auto_ctrl_in_a_bits_mask;
  wire [63:0]      auto_ctrl_in_a_bits_data_0 = auto_ctrl_in_a_bits_data;
  wire             auto_ctrl_in_a_bits_corrupt_0 = auto_ctrl_in_a_bits_corrupt;
  wire             auto_ctrl_in_d_ready_0 = auto_ctrl_in_d_ready;
  wire             io_flush_match_0 = io_flush_match;
  wire             io_flush_req_ready_0 = io_flush_req_ready;
  wire             io_flush_resp_0 = io_flush_resp;
  wire [1:0]       auto_ctrl_in_d_bits_param = 2'h0;
  wire [1:0]       ctrlnodeIn_d_bits_param = 2'h0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]       ctrlnodeIn_d_bits_d_param = 2'h0;	// src/main/scala/tilelink/Edges.scala:771:17
  wire [3:0][63:0] _GEN = '{64'h0, 64'h0, 64'h0, 64'h60A0801};	// src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rifireMux_out = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rifireMux_out_1 = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rifireMux_out_2 = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rifireMux_out_3 = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rifireMux = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_wifireMux_out = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_wifireMux_out_1 = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rofireMux_out = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rofireMux_out_1 = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rofireMux_out_2 = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rofireMux_out_3 = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_rofireMux = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_wofireMux_out = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_wofireMux_out_1 = 1'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire [11:0]      out_prepend = 12'h801;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [63:0]      ctrlnodeIn_d_bits_d_data = 64'h0;	// src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [2:0]       ctrlnodeIn_d_bits_d_opcode = 3'h0;	// src/main/scala/tilelink/Bundles.scala:259:74, src/main/scala/tilelink/Edges.scala:771:17
  wire [8:0]       out_maskMatch = 9'h1B7;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [19:0]      out_prepend_1 = 20'hA0801;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [26:0]      out_prepend_2 = 27'h60A0801;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             auto_ctrl_in_d_bits_sink = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             auto_ctrl_in_d_bits_denied = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             auto_ctrl_in_d_bits_corrupt = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             ctrlnodeIn_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire             ctrlnodeIn_d_bits_sink = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             ctrlnodeIn_d_bits_denied = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             ctrlnodeIn_d_bits_corrupt = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             ctrlnodeIn_d_bits_d_sink = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             ctrlnodeIn_d_bits_d_denied = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             ctrlnodeIn_d_bits_d_corrupt = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
  wire             ctrlnodeIn_a_valid = auto_ctrl_in_a_valid_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]       ctrlnodeIn_a_bits_opcode = auto_ctrl_in_a_bits_opcode_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]       ctrlnodeIn_a_bits_param = auto_ctrl_in_a_bits_param_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]       ctrlnodeIn_a_bits_size = auto_ctrl_in_a_bits_size_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [8:0]       ctrlnodeIn_a_bits_source = auto_ctrl_in_a_bits_source_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [25:0]      ctrlnodeIn_a_bits_address = auto_ctrl_in_a_bits_address_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [7:0]       ctrlnodeIn_a_bits_mask = auto_ctrl_in_a_bits_mask_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [63:0]      ctrlnodeIn_a_bits_data = auto_ctrl_in_a_bits_data_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire             ctrlnodeIn_a_bits_corrupt = auto_ctrl_in_a_bits_corrupt_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire             ctrlnodeIn_d_ready = auto_ctrl_in_d_ready_0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire             ctrlnodeIn_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]       ctrlnodeIn_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]       ctrlnodeIn_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [8:0]       ctrlnodeIn_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [63:0]      ctrlnodeIn_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire             in_ready;	// src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire             auto_ctrl_in_a_ready_0 = ctrlnodeIn_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire             in_valid = ctrlnodeIn_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire [1:0]       in_bits_extra_tlrr_extra_size = ctrlnodeIn_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire [8:0]       in_bits_extra_tlrr_extra_source = ctrlnodeIn_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire [7:0]       in_bits_mask = ctrlnodeIn_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire [63:0]      in_bits_data = ctrlnodeIn_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire             out_ready = ctrlnodeIn_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_valid;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             auto_ctrl_in_d_valid_0 = ctrlnodeIn_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]       auto_ctrl_in_d_bits_opcode_0 = ctrlnodeIn_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]       ctrlnodeIn_d_bits_d_size;	// src/main/scala/tilelink/Edges.scala:771:17
  wire [1:0]       auto_ctrl_in_d_bits_size_0 = ctrlnodeIn_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [8:0]       ctrlnodeIn_d_bits_d_source;	// src/main/scala/tilelink/Edges.scala:771:17
  wire [8:0]       auto_ctrl_in_d_bits_source_0 = ctrlnodeIn_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [63:0]      out_bits_data;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [63:0]      auto_ctrl_in_d_bits_data_0 = ctrlnodeIn_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  reg              flushInValid;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33
  wire             io_flush_req_valid_0 = flushInValid;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33
  reg  [63:0]      flushInAddress;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:46:29
  wire [63:0]      io_flush_req_bits_0 = flushInAddress;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:46:29
  reg              flushOutValid;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:47:33
  assign ctrlnodeIn_a_ready = in_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:68:18
  wire             out_front_bits_read = in_bits_read;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  wire [8:0]       out_front_bits_index = in_bits_index;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  wire [63:0]      out_front_bits_data = in_bits_data;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  wire [7:0]       out_front_bits_mask = in_bits_mask;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  wire [8:0]       out_front_bits_extra_tlrr_extra_source =
    in_bits_extra_tlrr_extra_source;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  wire [1:0]       out_front_bits_extra_tlrr_extra_size = in_bits_extra_tlrr_extra_size;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  assign in_bits_read = ctrlnodeIn_a_bits_opcode == 3'h4;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:68:18, :69:36
  assign in_bits_index = ctrlnodeIn_a_bits_address[11:3];	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:193:34, src/main/scala/tilelink/RegisterRouter.scala:68:18, :70:19
  assign ctrlnodeIn_d_valid = out_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign ctrlnodeIn_d_bits_data = out_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign ctrlnodeIn_d_bits_d_source = out_bits_extra_tlrr_extra_source;	// src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign ctrlnodeIn_d_bits_d_size = out_bits_extra_tlrr_extra_size;	// src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [8:0]       out_findex = out_front_bits_index & 9'h1B7;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [8:0]       out_bindex = _out_back_q_io_deq_bits_index & 9'h1B7;	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [15:0]      out_frontMask_lo_lo =
    {{8{out_front_bits_mask[1]}}, {8{out_front_bits_mask[0]}}};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [15:0]      out_frontMask_lo_hi =
    {{8{out_front_bits_mask[3]}}, {8{out_front_bits_mask[2]}}};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [31:0]      out_frontMask_lo = {out_frontMask_lo_hi, out_frontMask_lo_lo};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [15:0]      out_frontMask_hi_lo =
    {{8{out_front_bits_mask[5]}}, {8{out_front_bits_mask[4]}}};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [15:0]      out_frontMask_hi_hi =
    {{8{out_front_bits_mask[7]}}, {8{out_front_bits_mask[6]}}};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [31:0]      out_frontMask_hi = {out_frontMask_hi_hi, out_frontMask_hi_lo};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [63:0]      out_frontMask = {out_frontMask_hi, out_frontMask_lo};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [15:0]      out_backMask_lo_lo =
    {{8{_out_back_q_io_deq_bits_mask[1]}}, {8{_out_back_q_io_deq_bits_mask[0]}}};	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [15:0]      out_backMask_lo_hi =
    {{8{_out_back_q_io_deq_bits_mask[3]}}, {8{_out_back_q_io_deq_bits_mask[2]}}};	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [31:0]      out_backMask_lo = {out_backMask_lo_hi, out_backMask_lo_lo};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [15:0]      out_backMask_hi_lo =
    {{8{_out_back_q_io_deq_bits_mask[5]}}, {8{_out_back_q_io_deq_bits_mask[4]}}};	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [15:0]      out_backMask_hi_hi =
    {{8{_out_back_q_io_deq_bits_mask[7]}}, {8{_out_back_q_io_deq_bits_mask[6]}}};	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [31:0]      out_backMask_hi = {out_backMask_hi_hi, out_backMask_hi_lo};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [63:0]      out_backMask = {out_backMask_hi, out_backMask_lo};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rimask = |(out_frontMask[7:0]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wimask = &(out_frontMask[7:0]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_romask = |(out_backMask[7:0]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_womask = &(out_backMask[7:0]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rivalid_0;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_rivalid = out_rivalid_0 & out_rimask;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_roready_0;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_roready = out_roready_0 & out_romask;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wivalid_0;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_wivalid = out_wivalid_0 & out_wimask;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_woready_0;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_woready = out_woready_0 & out_womask;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rimask_1 = |(out_frontMask[15:8]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wimask_1 = &(out_frontMask[15:8]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_romask_1 = |(out_backMask[15:8]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_womask_1 = &(out_backMask[15:8]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rivalid_1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_rivalid_1 = out_rivalid_1 & out_rimask_1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_roready_1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_roready_1 = out_roready_1 & out_romask_1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wivalid_1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_wivalid_1 = out_wivalid_1 & out_wimask_1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_woready_1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_woready_1 = out_woready_1 & out_womask_1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rimask_2 = |(out_frontMask[23:16]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wimask_2 = &(out_frontMask[23:16]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_romask_2 = |(out_backMask[23:16]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_womask_2 = &(out_backMask[23:16]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rivalid_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_rivalid_2 = out_rivalid_2 & out_rimask_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_roready_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_roready_2 = out_roready_2 & out_romask_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wivalid_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_wivalid_2 = out_wivalid_2 & out_wimask_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_woready_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_woready_2 = out_woready_2 & out_womask_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rimask_3 = |(out_frontMask[31:24]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wimask_3 = &(out_frontMask[31:24]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_romask_3 = |(out_backMask[31:24]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_womask_3 = &(out_backMask[31:24]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rivalid_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_rivalid_3 = out_rivalid_3 & out_rimask_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_roready_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_roready_3 = out_roready_3 & out_romask_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wivalid_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_wivalid_3 = out_wivalid_3 & out_wimask_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_woready_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_woready_3 = out_woready_3 & out_womask_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rimask_4 = |out_frontMask;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wimask_4 = &out_frontMask;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_romask_4 = |out_backMask;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_womask_4 = &out_backMask;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rivalid_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_rivalid_4 = out_rivalid_4 & out_rimask_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_roready_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_roready_4 = out_roready_4 & out_romask_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wivalid_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_wivalid_4 = out_wivalid_4 & out_wimask_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_woready_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_woready_4 = out_woready_4 & out_womask_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_wiready = ~flushInValid;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33, :71:23, :72:8
  wire             out_wifireMux_out_2 = out_f_wiready | ~out_wimask_4;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:72:8, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wofireMux_out_2 = flushOutValid | ~out_womask_4;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:47:33, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rimask_5 = |(out_frontMask[31:0]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wimask_5 = &(out_frontMask[31:0]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_romask_5 = |(out_backMask[31:0]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_womask_5 = &(out_backMask[31:0]);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_rivalid_5;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_rivalid_5 = out_rivalid_5 & out_rimask_5;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_roready_5;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_roready_5 = out_roready_5 & out_romask_5;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wivalid_5;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_wivalid_5 = out_wivalid_5 & out_wimask_5;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_woready_5;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_woready_5 = out_woready_5 & out_womask_5;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             flushOutReady = out_f_woready_5 | out_f_woready_4;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:48:34, :62:{21,37}, :69:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_f_wiready_1 = ~flushInValid;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33, :65:8, :71:23
  wire             out_wifireMux_out_3 = out_f_wiready_1 | ~out_wimask_5;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:65:8, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wofireMux_out_3 = flushOutValid | ~out_womask_5;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:47:33, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [1:0]       out_iindex = {out_front_bits_index[6], out_front_bits_index[3]};	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [1:0]       out_oindex =
    {_out_back_q_io_deq_bits_index[6], _out_back_q_io_deq_bits_index[3]};	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_frontSel_0 = out_iindex == 2'h0;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_frontSel_1 = out_iindex == 2'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_frontSel_2 = out_iindex == 2'h2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_frontSel_3 = &out_iindex;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_backSel_0 = out_oindex == 2'h0;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_backSel_1 = out_oindex == 2'h1;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_backSel_2 = out_oindex == 2'h2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_backSel_3 = &out_oindex;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_front_ready;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             _out_wifireMux_T = in_valid & out_front_ready;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  wire             _out_rifireMux_T_1 = _out_wifireMux_T & out_front_bits_read;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             _out_rifireMux_T_3 =
    _out_rifireMux_T_1 & out_frontSel_0 & ~(|out_findex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_rivalid_0 = _out_rifireMux_T_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_rivalid_1 = _out_rifireMux_T_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_rivalid_2 = _out_rifireMux_T_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_rivalid_3 = _out_rifireMux_T_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_rivalid_4 = _out_rifireMux_T_1 & out_frontSel_2 & ~(|out_findex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_rivalid_5 = _out_rifireMux_T_1 & out_frontSel_3 & ~(|out_findex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             _out_wifireMux_T_2 = _out_wifireMux_T & ~out_front_bits_read;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             _out_wifireMux_T_4 =
    _out_wifireMux_T_2 & out_frontSel_0 & ~(|out_findex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_wivalid_0 = _out_wifireMux_T_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_wivalid_1 = _out_wifireMux_T_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_wivalid_2 = _out_wifireMux_T_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_wivalid_3 = _out_wifireMux_T_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_wivalid_4 = _out_wifireMux_T_2 & out_frontSel_2 & ~(|out_findex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wifireMux_all = out_wivalid_4 & out_wifireMux_out_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/ReduceOthers.scala:47:21
  assign out_wivalid_5 = _out_wifireMux_T_2 & out_frontSel_3 & ~(|out_findex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wifireMux_all_1 = out_wivalid_5 & out_wifireMux_out_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/ReduceOthers.scala:47:21
  wire [3:0]       _GEN_0 =
    {{out_wifireMux_out_3 | (|out_findex)},
     {out_wifireMux_out_2 | (|out_findex)},
     {1'h1},
     {1'h1}};	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_wifireMux = _GEN_0[out_iindex];	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             _out_wofireMux_T = _out_back_q_io_deq_valid & out_ready;	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             _out_rofireMux_T_1 = _out_wofireMux_T & _out_back_q_io_deq_bits_read;	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             _out_rofireMux_T_3 =
    _out_rofireMux_T_1 & out_backSel_0 & ~(|out_bindex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_roready_0 = _out_rofireMux_T_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_roready_1 = _out_rofireMux_T_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_roready_2 = _out_rofireMux_T_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_roready_3 = _out_rofireMux_T_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_roready_4 = _out_rofireMux_T_1 & out_backSel_2 & ~(|out_bindex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_roready_5 = _out_rofireMux_T_1 & out_backSel_3 & ~(|out_bindex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             _out_wofireMux_T_2 = _out_wofireMux_T & ~_out_back_q_io_deq_bits_read;	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             _out_wofireMux_T_4 =
    _out_wofireMux_T_2 & out_backSel_0 & ~(|out_bindex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_woready_0 = _out_wofireMux_T_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_woready_1 = _out_wofireMux_T_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_woready_2 = _out_wofireMux_T_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_woready_3 = _out_wofireMux_T_4;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign out_woready_4 = _out_wofireMux_T_2 & out_backSel_2 & ~(|out_bindex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wofireMux_all = out_woready_4 & out_wofireMux_out_2;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/ReduceOthers.scala:47:21
  assign out_woready_5 = _out_wofireMux_T_2 & out_backSel_3 & ~(|out_bindex);	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire             out_wofireMux_all_1 = out_woready_5 & out_wofireMux_out_3;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/ReduceOthers.scala:47:21
  wire [3:0]       _GEN_1 =
    {{out_wofireMux_out_3 | (|out_bindex)},
     {out_wofireMux_out_2 | (|out_bindex)},
     {1'h1},
     {1'h1}};	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_wofireMux = _GEN_1[out_oindex];	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_iready = out_front_bits_read | out_wifireMux;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  wire             out_oready = _out_back_q_io_deq_bits_read | out_wofireMux;	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  assign in_ready = out_front_ready & out_iready;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  wire             out_front_valid = in_valid & out_iready;	// src/main/scala/tilelink/RegisterRouter.scala:68:18, :82:24
  assign out_valid = _out_back_q_io_deq_valid & out_oready;	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  wire [3:0]       _GEN_2 =
    {{~(|out_bindex)}, {~(|out_bindex)}, {1'h1}, {~(|out_bindex)}};	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  assign out_bits_data = _GEN_2[out_oindex] ? _GEN[out_oindex] : 64'h0;	// src/main/scala/tilelink/RegisterRouter.scala:82:24, src/main/scala/util/MuxLiteral.scala:49:10
  assign ctrlnodeIn_d_bits_size = ctrlnodeIn_d_bits_d_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17
  assign ctrlnodeIn_d_bits_source = ctrlnodeIn_d_bits_d_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/Edges.scala:771:17
  wire             out_bits_read;	// src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign ctrlnodeIn_d_bits_opcode = {2'h0, out_bits_read};	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/tilelink/RegisterRouter.scala:82:24, :100:19
  always @(posedge clock) begin
    if (reset) begin
      flushInValid <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
      flushOutValid <= 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:367:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:47:33, src/main/scala/tilelink/Edges.scala:771:17, src/main/scala/tilelink/Nodes.scala:24:25
    end
    else begin
      automatic logic _GEN_3;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:56:27
      _GEN_3 = ~io_flush_match_0 & flushInValid;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33, :56:{11,27}
      flushInValid <=
        out_f_wivalid_5 | out_f_wivalid_4 | ~(_GEN_3 | io_flush_req_ready_0)
        & flushInValid;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33, :52:{31,46}, :56:{27,44}, :57:20, :63:{21,36}, :70:{21,36}, src/main/scala/tilelink/RegisterRouter.scala:82:24
      flushOutValid <= _GEN_3 | io_flush_resp_0 | ~flushOutReady & flushOutValid;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:47:33, :48:34, :50:{26,42}, :51:{26,42}, :56:{27,44}, :58:21
    end
    if (out_f_wivalid_5 & ~flushInValid)	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33, :64:20, :71:23, src/main/scala/tilelink/RegisterRouter.scala:82:24
      flushInAddress <= {28'h0, out_front_bits_data[31:0], 4'h0};	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:46:29, :64:{55,63}, src/main/scala/tilelink/RegisterRouter.scala:82:24
    else if (out_f_wivalid_4 & ~flushInValid)	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33, :71:{20,23}, src/main/scala/tilelink/RegisterRouter.scala:82:24
      flushInAddress <= out_front_bits_data;	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:46:29, src/main/scala/tilelink/RegisterRouter.scala:82:24
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin
      automatic logic [31:0] _RANDOM[0:2];
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;
        end
        flushInValid = _RANDOM[2'h0][0];	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33
        flushInAddress = {_RANDOM[2'h0][31:1], _RANDOM[2'h1], _RANDOM[2'h2][0]};	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:45:33, :46:29
        flushOutValid = _RANDOM[2'h2][1];	// src/main/scala/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Control.scala:46:29, :47:33
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_29 monitor (	// src/main/scala/tilelink/Nodes.scala:24:25
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (ctrlnodeIn_a_ready),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_valid        (ctrlnodeIn_a_valid),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_opcode  (ctrlnodeIn_a_bits_opcode),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_param   (ctrlnodeIn_a_bits_param),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_size    (ctrlnodeIn_a_bits_size),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_source  (ctrlnodeIn_a_bits_source),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_address (ctrlnodeIn_a_bits_address),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_mask    (ctrlnodeIn_a_bits_mask),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_data    (ctrlnodeIn_a_bits_data),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_a_bits_corrupt (ctrlnodeIn_a_bits_corrupt),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_ready        (ctrlnodeIn_d_ready),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_valid        (ctrlnodeIn_d_valid),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_opcode  (ctrlnodeIn_d_bits_opcode),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_size    (ctrlnodeIn_d_bits_size),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_source  (ctrlnodeIn_d_bits_source),	// src/main/scala/diplomacy/Nodes.scala:1214:17
    .io_in_d_bits_data    (ctrlnodeIn_d_bits_data)	// src/main/scala/diplomacy/Nodes.scala:1214:17
  );
  Queue_91 out_back_q (	// src/main/scala/chisel3/util/Decoupled.scala:376:21
    .clock                               (clock),
    .reset                               (reset),
    .io_enq_ready                        (out_front_ready),
    .io_enq_valid                        (out_front_valid),	// src/main/scala/tilelink/RegisterRouter.scala:82:24
    .io_enq_bits_read                    (out_front_bits_read),	// src/main/scala/tilelink/RegisterRouter.scala:82:24
    .io_enq_bits_index                   (out_front_bits_index),	// src/main/scala/tilelink/RegisterRouter.scala:82:24
    .io_enq_bits_data                    (out_front_bits_data),	// src/main/scala/tilelink/RegisterRouter.scala:82:24
    .io_enq_bits_mask                    (out_front_bits_mask),	// src/main/scala/tilelink/RegisterRouter.scala:82:24
    .io_enq_bits_extra_tlrr_extra_source (out_front_bits_extra_tlrr_extra_source),	// src/main/scala/tilelink/RegisterRouter.scala:82:24
    .io_enq_bits_extra_tlrr_extra_size   (out_front_bits_extra_tlrr_extra_size),	// src/main/scala/tilelink/RegisterRouter.scala:82:24
    .io_deq_ready                        (out_ready & out_oready),	// src/main/scala/tilelink/RegisterRouter.scala:82:24
    .io_deq_valid                        (_out_back_q_io_deq_valid),
    .io_deq_bits_read                    (_out_back_q_io_deq_bits_read),
    .io_deq_bits_index                   (_out_back_q_io_deq_bits_index),
    .io_deq_bits_mask                    (_out_back_q_io_deq_bits_mask),
    .io_deq_bits_extra_tlrr_extra_source (out_bits_extra_tlrr_extra_source),
    .io_deq_bits_extra_tlrr_extra_size   (out_bits_extra_tlrr_extra_size)
  );
  assign out_bits_read = _out_back_q_io_deq_bits_read;	// src/main/scala/chisel3/util/Decoupled.scala:376:21, src/main/scala/tilelink/RegisterRouter.scala:82:24
  assign auto_ctrl_in_a_ready = auto_ctrl_in_a_ready_0;
  assign auto_ctrl_in_d_valid = auto_ctrl_in_d_valid_0;
  assign auto_ctrl_in_d_bits_opcode = auto_ctrl_in_d_bits_opcode_0;
  assign auto_ctrl_in_d_bits_size = auto_ctrl_in_d_bits_size_0;
  assign auto_ctrl_in_d_bits_source = auto_ctrl_in_d_bits_source_0;
  assign auto_ctrl_in_d_bits_data = auto_ctrl_in_d_bits_data_0;
  assign io_flush_req_valid = io_flush_req_valid_0;
  assign io_flush_req_bits = io_flush_req_bits_0;
endmodule

