// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLDebugModule(
  output        auto_dmInner_dmInner_tl_in_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input         auto_dmInner_dmInner_tl_in_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [2:0]  auto_dmInner_dmInner_tl_in_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmInner_dmInner_tl_in_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [1:0]  auto_dmInner_dmInner_tl_in_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [9:0]  auto_dmInner_dmInner_tl_in_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [11:0] auto_dmInner_dmInner_tl_in_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [7:0]  auto_dmInner_dmInner_tl_in_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [63:0] auto_dmInner_dmInner_tl_in_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input         auto_dmInner_dmInner_tl_in_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmInner_dmInner_tl_in_d_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output        auto_dmInner_dmInner_tl_in_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [2:0]  auto_dmInner_dmInner_tl_in_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [1:0]  auto_dmInner_dmInner_tl_in_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [9:0]  auto_dmInner_dmInner_tl_in_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [63:0] auto_dmInner_dmInner_tl_in_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output        auto_dmOuter_intsource_out_7_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmOuter_intsource_out_6_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmOuter_intsource_out_5_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmOuter_intsource_out_4_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmOuter_intsource_out_3_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmOuter_intsource_out_2_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmOuter_intsource_out_1_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_dmOuter_intsource_out_0_sync_0,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input         io_debug_clock,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_debug_reset,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_tl_clock,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_tl_reset,	// src/main/scala/devices/debug/Debug.scala:1960:16
  output        io_ctrl_ndreset,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_ctrl_dmactive,	// src/main/scala/devices/debug/Debug.scala:1960:16
  input         io_ctrl_dmactiveAck,	// src/main/scala/devices/debug/Debug.scala:1960:16
  output        io_dmi_dmi_req_ready,	// src/main/scala/devices/debug/Debug.scala:1960:16
  input         io_dmi_dmi_req_valid,	// src/main/scala/devices/debug/Debug.scala:1960:16
  input  [6:0]  io_dmi_dmi_req_bits_addr,	// src/main/scala/devices/debug/Debug.scala:1960:16
  input  [31:0] io_dmi_dmi_req_bits_data,	// src/main/scala/devices/debug/Debug.scala:1960:16
  input  [1:0]  io_dmi_dmi_req_bits_op,	// src/main/scala/devices/debug/Debug.scala:1960:16
  input         io_dmi_dmi_resp_ready,	// src/main/scala/devices/debug/Debug.scala:1960:16
  output        io_dmi_dmi_resp_valid,	// src/main/scala/devices/debug/Debug.scala:1960:16
  output [31:0] io_dmi_dmi_resp_bits_data,	// src/main/scala/devices/debug/Debug.scala:1960:16
  output [1:0]  io_dmi_dmi_resp_bits_resp,	// src/main/scala/devices/debug/Debug.scala:1960:16
  input         io_dmi_dmiClock,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_dmi_dmiReset,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_hartIsInReset_0,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_hartIsInReset_1,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_hartIsInReset_2,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_hartIsInReset_3,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_hartIsInReset_4,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_hartIsInReset_5,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_hartIsInReset_6,	// src/main/scala/devices/debug/Debug.scala:1960:16
                io_hartIsInReset_7	// src/main/scala/devices/debug/Debug.scala:1960:16
);

  wire [63:0] auto_dmInner_dmInner_tl_in_d_bits_data_0;
  wire [9:0]  auto_dmInner_dmInner_tl_in_d_bits_source_0;
  wire [1:0]  auto_dmInner_dmInner_tl_in_d_bits_size_0;
  wire [2:0]  auto_dmInner_dmInner_tl_in_d_bits_opcode_0;
  wire        auto_dmInner_dmInner_tl_in_d_valid_0;
  wire        auto_dmInner_dmInner_tl_in_a_ready_0;
  wire [1:0]  io_dmi_dmi_resp_bits_resp_0;
  wire [31:0] io_dmi_dmi_resp_bits_data_0;
  wire        io_dmi_dmi_resp_valid_0;
  wire        io_dmi_dmi_req_ready_0;
  wire        io_ctrl_ndreset_0;
  wire        auto_dmOuter_intsource_out_0_sync_0_0;
  wire        auto_dmOuter_intsource_out_1_sync_0_0;
  wire        auto_dmOuter_intsource_out_2_sync_0_0;
  wire        auto_dmOuter_intsource_out_3_sync_0_0;
  wire        auto_dmOuter_intsource_out_4_sync_0_0;
  wire        auto_dmOuter_intsource_out_5_sync_0_0;
  wire        auto_dmOuter_intsource_out_6_sync_0_0;
  wire        auto_dmOuter_intsource_out_7_sync_0_0;
  wire        _dmInner_auto_dmiXing_in_a_ridx;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_auto_dmiXing_in_a_safe_ridx_valid;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_auto_dmiXing_in_a_safe_sink_reset_n;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire [2:0]  _dmInner_auto_dmiXing_in_d_mem_0_opcode;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire [1:0]  _dmInner_auto_dmiXing_in_d_mem_0_size;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_auto_dmiXing_in_d_mem_0_source;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire [31:0] _dmInner_auto_dmiXing_in_d_mem_0_data;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_auto_dmiXing_in_d_widx;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_auto_dmiXing_in_d_safe_widx_valid;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_auto_dmiXing_in_d_safe_source_reset_n;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_innerCtrl_ridx;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_innerCtrl_safe_ridx_valid;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_innerCtrl_safe_sink_reset_n;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_hgDebugInt_0;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_hgDebugInt_1;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_hgDebugInt_2;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_hgDebugInt_3;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_hgDebugInt_4;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_hgDebugInt_5;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_hgDebugInt_6;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire        _dmInner_io_hgDebugInt_7;	// src/main/scala/devices/debug/Debug.scala:1942:53
  wire [2:0]  _dmOuter_auto_asource_out_a_mem_0_opcode;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire [8:0]  _dmOuter_auto_asource_out_a_mem_0_address;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire [31:0] _dmOuter_auto_asource_out_a_mem_0_data;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_auto_asource_out_a_widx;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_auto_asource_out_a_safe_widx_valid;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_auto_asource_out_a_safe_source_reset_n;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_auto_asource_out_d_ridx;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_auto_asource_out_d_safe_ridx_valid;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_auto_asource_out_d_safe_sink_reset_n;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_ctrl_dmactive;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_resumereq;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire [9:0]  _dmOuter_io_innerCtrl_mem_0_hartsel;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_ackhavereset;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hasel;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hamask_0;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hamask_1;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hamask_2;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hamask_3;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hamask_4;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hamask_5;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hamask_6;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hamask_7;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hrmask_0;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hrmask_1;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hrmask_2;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hrmask_3;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hrmask_4;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hrmask_5;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hrmask_6;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_mem_0_hrmask_7;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_widx;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_safe_widx_valid;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        _dmOuter_io_innerCtrl_safe_source_reset_n;	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        auto_dmInner_dmInner_tl_in_a_valid_0 = auto_dmInner_dmInner_tl_in_a_valid;
  wire [2:0]  auto_dmInner_dmInner_tl_in_a_bits_opcode_0 =
    auto_dmInner_dmInner_tl_in_a_bits_opcode;
  wire [2:0]  auto_dmInner_dmInner_tl_in_a_bits_param_0 =
    auto_dmInner_dmInner_tl_in_a_bits_param;
  wire [1:0]  auto_dmInner_dmInner_tl_in_a_bits_size_0 =
    auto_dmInner_dmInner_tl_in_a_bits_size;
  wire [9:0]  auto_dmInner_dmInner_tl_in_a_bits_source_0 =
    auto_dmInner_dmInner_tl_in_a_bits_source;
  wire [11:0] auto_dmInner_dmInner_tl_in_a_bits_address_0 =
    auto_dmInner_dmInner_tl_in_a_bits_address;
  wire [7:0]  auto_dmInner_dmInner_tl_in_a_bits_mask_0 =
    auto_dmInner_dmInner_tl_in_a_bits_mask;
  wire [63:0] auto_dmInner_dmInner_tl_in_a_bits_data_0 =
    auto_dmInner_dmInner_tl_in_a_bits_data;
  wire        auto_dmInner_dmInner_tl_in_a_bits_corrupt_0 =
    auto_dmInner_dmInner_tl_in_a_bits_corrupt;
  wire        auto_dmInner_dmInner_tl_in_d_ready_0 = auto_dmInner_dmInner_tl_in_d_ready;
  wire        io_debug_clock_0 = io_debug_clock;
  wire        io_debug_reset_0 = io_debug_reset;
  wire        io_tl_clock_0 = io_tl_clock;
  wire        io_tl_reset_0 = io_tl_reset;
  wire        io_ctrl_dmactiveAck_0 = io_ctrl_dmactiveAck;
  wire        io_dmi_dmi_req_valid_0 = io_dmi_dmi_req_valid;
  wire [6:0]  io_dmi_dmi_req_bits_addr_0 = io_dmi_dmi_req_bits_addr;
  wire [31:0] io_dmi_dmi_req_bits_data_0 = io_dmi_dmi_req_bits_data;
  wire [1:0]  io_dmi_dmi_req_bits_op_0 = io_dmi_dmi_req_bits_op;
  wire        io_dmi_dmi_resp_ready_0 = io_dmi_dmi_resp_ready;
  wire        io_dmi_dmiClock_0 = io_dmi_dmiClock;
  wire        io_dmi_dmiReset_0 = io_dmi_dmiReset;
  wire        io_hartIsInReset_0_0 = io_hartIsInReset_0;
  wire        io_hartIsInReset_1_0 = io_hartIsInReset_1;
  wire        io_hartIsInReset_2_0 = io_hartIsInReset_2;
  wire        io_hartIsInReset_3_0 = io_hartIsInReset_3;
  wire        io_hartIsInReset_4_0 = io_hartIsInReset_4;
  wire        io_hartIsInReset_5_0 = io_hartIsInReset_5;
  wire        io_hartIsInReset_6_0 = io_hartIsInReset_6;
  wire        io_hartIsInReset_7_0 = io_hartIsInReset_7;
  wire [1:0]  auto_dmInner_dmInner_tl_in_d_bits_param = 2'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        auto_dmInner_dmInner_custom_in_addr = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        auto_dmInner_dmInner_custom_in_ready = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        auto_dmInner_dmInner_custom_in_valid = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        auto_dmInner_dmInner_tl_in_d_bits_sink = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        auto_dmInner_dmInner_tl_in_d_bits_denied = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        auto_dmInner_dmInner_tl_in_d_bits_corrupt = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        io_ctrl_debugUnavail_0 = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        io_ctrl_debugUnavail_1 = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        io_ctrl_debugUnavail_2 = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        io_ctrl_debugUnavail_3 = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        io_ctrl_debugUnavail_4 = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        io_ctrl_debugUnavail_5 = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        io_ctrl_debugUnavail_6 = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        io_ctrl_debugUnavail_7 = 1'h0;	// src/main/scala/devices/debug/Debug.scala:1941:53, :1942:53, :1960:16, src/main/scala/diplomacy/LazyModule.scala:374:18
  wire        childClock = io_tl_clock_0;	// src/main/scala/diplomacy/LazyModule.scala:419:31
  wire        childReset = io_tl_reset_0;	// src/main/scala/diplomacy/LazyModule.scala:421:31
  TLDebugModuleOuterAsync dmOuter (	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_asource_out_a_mem_0_opcode        (_dmOuter_auto_asource_out_a_mem_0_opcode),
    .auto_asource_out_a_mem_0_address       (_dmOuter_auto_asource_out_a_mem_0_address),
    .auto_asource_out_a_mem_0_data          (_dmOuter_auto_asource_out_a_mem_0_data),
    .auto_asource_out_a_ridx                (_dmInner_auto_dmiXing_in_a_ridx),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_a_widx                (_dmOuter_auto_asource_out_a_widx),
    .auto_asource_out_a_safe_ridx_valid     (_dmInner_auto_dmiXing_in_a_safe_ridx_valid),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_a_safe_widx_valid     (_dmOuter_auto_asource_out_a_safe_widx_valid),
    .auto_asource_out_a_safe_source_reset_n
      (_dmOuter_auto_asource_out_a_safe_source_reset_n),
    .auto_asource_out_a_safe_sink_reset_n
      (_dmInner_auto_dmiXing_in_a_safe_sink_reset_n),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_d_mem_0_opcode        (_dmInner_auto_dmiXing_in_d_mem_0_opcode),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_d_mem_0_size          (_dmInner_auto_dmiXing_in_d_mem_0_size),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_d_mem_0_source        (_dmInner_auto_dmiXing_in_d_mem_0_source),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_d_mem_0_data          (_dmInner_auto_dmiXing_in_d_mem_0_data),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_d_ridx                (_dmOuter_auto_asource_out_d_ridx),
    .auto_asource_out_d_widx                (_dmInner_auto_dmiXing_in_d_widx),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_d_safe_ridx_valid     (_dmOuter_auto_asource_out_d_safe_ridx_valid),
    .auto_asource_out_d_safe_widx_valid     (_dmInner_auto_dmiXing_in_d_safe_widx_valid),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_d_safe_source_reset_n
      (_dmInner_auto_dmiXing_in_d_safe_source_reset_n),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_asource_out_d_safe_sink_reset_n
      (_dmOuter_auto_asource_out_d_safe_sink_reset_n),
    .auto_intsource_out_7_sync_0            (auto_dmOuter_intsource_out_7_sync_0_0),
    .auto_intsource_out_6_sync_0            (auto_dmOuter_intsource_out_6_sync_0_0),
    .auto_intsource_out_5_sync_0            (auto_dmOuter_intsource_out_5_sync_0_0),
    .auto_intsource_out_4_sync_0            (auto_dmOuter_intsource_out_4_sync_0_0),
    .auto_intsource_out_3_sync_0            (auto_dmOuter_intsource_out_3_sync_0_0),
    .auto_intsource_out_2_sync_0            (auto_dmOuter_intsource_out_2_sync_0_0),
    .auto_intsource_out_1_sync_0            (auto_dmOuter_intsource_out_1_sync_0_0),
    .auto_intsource_out_0_sync_0            (auto_dmOuter_intsource_out_0_sync_0_0),
    .io_dmi_clock                           (io_dmi_dmiClock_0),
    .io_dmi_reset                           (io_dmi_dmiReset_0),
    .io_dmi_req_ready                       (io_dmi_dmi_req_ready_0),
    .io_dmi_req_valid                       (io_dmi_dmi_req_valid_0),
    .io_dmi_req_bits_addr                   (io_dmi_dmi_req_bits_addr_0),
    .io_dmi_req_bits_data                   (io_dmi_dmi_req_bits_data_0),
    .io_dmi_req_bits_op                     (io_dmi_dmi_req_bits_op_0),
    .io_dmi_resp_ready                      (io_dmi_dmi_resp_ready_0),
    .io_dmi_resp_valid                      (io_dmi_dmi_resp_valid_0),
    .io_dmi_resp_bits_data                  (io_dmi_dmi_resp_bits_data_0),
    .io_dmi_resp_bits_resp                  (io_dmi_dmi_resp_bits_resp_0),
    .io_ctrl_ndreset                        (io_ctrl_ndreset_0),
    .io_ctrl_dmactive                       (_dmOuter_io_ctrl_dmactive),
    .io_ctrl_dmactiveAck                    (io_ctrl_dmactiveAck_0),
    .io_innerCtrl_mem_0_resumereq           (_dmOuter_io_innerCtrl_mem_0_resumereq),
    .io_innerCtrl_mem_0_hartsel             (_dmOuter_io_innerCtrl_mem_0_hartsel),
    .io_innerCtrl_mem_0_ackhavereset        (_dmOuter_io_innerCtrl_mem_0_ackhavereset),
    .io_innerCtrl_mem_0_hasel               (_dmOuter_io_innerCtrl_mem_0_hasel),
    .io_innerCtrl_mem_0_hamask_0            (_dmOuter_io_innerCtrl_mem_0_hamask_0),
    .io_innerCtrl_mem_0_hamask_1            (_dmOuter_io_innerCtrl_mem_0_hamask_1),
    .io_innerCtrl_mem_0_hamask_2            (_dmOuter_io_innerCtrl_mem_0_hamask_2),
    .io_innerCtrl_mem_0_hamask_3            (_dmOuter_io_innerCtrl_mem_0_hamask_3),
    .io_innerCtrl_mem_0_hamask_4            (_dmOuter_io_innerCtrl_mem_0_hamask_4),
    .io_innerCtrl_mem_0_hamask_5            (_dmOuter_io_innerCtrl_mem_0_hamask_5),
    .io_innerCtrl_mem_0_hamask_6            (_dmOuter_io_innerCtrl_mem_0_hamask_6),
    .io_innerCtrl_mem_0_hamask_7            (_dmOuter_io_innerCtrl_mem_0_hamask_7),
    .io_innerCtrl_mem_0_hrmask_0            (_dmOuter_io_innerCtrl_mem_0_hrmask_0),
    .io_innerCtrl_mem_0_hrmask_1            (_dmOuter_io_innerCtrl_mem_0_hrmask_1),
    .io_innerCtrl_mem_0_hrmask_2            (_dmOuter_io_innerCtrl_mem_0_hrmask_2),
    .io_innerCtrl_mem_0_hrmask_3            (_dmOuter_io_innerCtrl_mem_0_hrmask_3),
    .io_innerCtrl_mem_0_hrmask_4            (_dmOuter_io_innerCtrl_mem_0_hrmask_4),
    .io_innerCtrl_mem_0_hrmask_5            (_dmOuter_io_innerCtrl_mem_0_hrmask_5),
    .io_innerCtrl_mem_0_hrmask_6            (_dmOuter_io_innerCtrl_mem_0_hrmask_6),
    .io_innerCtrl_mem_0_hrmask_7            (_dmOuter_io_innerCtrl_mem_0_hrmask_7),
    .io_innerCtrl_ridx                      (_dmInner_io_innerCtrl_ridx),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_innerCtrl_widx                      (_dmOuter_io_innerCtrl_widx),
    .io_innerCtrl_safe_ridx_valid           (_dmInner_io_innerCtrl_safe_ridx_valid),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_innerCtrl_safe_widx_valid           (_dmOuter_io_innerCtrl_safe_widx_valid),
    .io_innerCtrl_safe_source_reset_n       (_dmOuter_io_innerCtrl_safe_source_reset_n),
    .io_innerCtrl_safe_sink_reset_n         (_dmInner_io_innerCtrl_safe_sink_reset_n),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_hgDebugInt_0                        (_dmInner_io_hgDebugInt_0),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_hgDebugInt_1                        (_dmInner_io_hgDebugInt_1),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_hgDebugInt_2                        (_dmInner_io_hgDebugInt_2),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_hgDebugInt_3                        (_dmInner_io_hgDebugInt_3),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_hgDebugInt_4                        (_dmInner_io_hgDebugInt_4),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_hgDebugInt_5                        (_dmInner_io_hgDebugInt_5),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_hgDebugInt_6                        (_dmInner_io_hgDebugInt_6),	// src/main/scala/devices/debug/Debug.scala:1942:53
    .io_hgDebugInt_7                        (_dmInner_io_hgDebugInt_7)	// src/main/scala/devices/debug/Debug.scala:1942:53
  );	// src/main/scala/devices/debug/Debug.scala:1941:53
  wire        io_ctrl_dmactive_0;
  assign io_ctrl_dmactive_0 = _dmOuter_io_ctrl_dmactive;	// src/main/scala/devices/debug/Debug.scala:1941:53
  TLDebugModuleInnerAsync dmInner (	// src/main/scala/devices/debug/Debug.scala:1942:53
    .auto_dmiXing_in_a_mem_0_opcode        (_dmOuter_auto_asource_out_a_mem_0_opcode),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmiXing_in_a_mem_0_address       (_dmOuter_auto_asource_out_a_mem_0_address),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmiXing_in_a_mem_0_data          (_dmOuter_auto_asource_out_a_mem_0_data),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmiXing_in_a_ridx                (_dmInner_auto_dmiXing_in_a_ridx),
    .auto_dmiXing_in_a_widx                (_dmOuter_auto_asource_out_a_widx),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmiXing_in_a_safe_ridx_valid     (_dmInner_auto_dmiXing_in_a_safe_ridx_valid),
    .auto_dmiXing_in_a_safe_widx_valid     (_dmOuter_auto_asource_out_a_safe_widx_valid),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmiXing_in_a_safe_source_reset_n
      (_dmOuter_auto_asource_out_a_safe_source_reset_n),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmiXing_in_a_safe_sink_reset_n   (_dmInner_auto_dmiXing_in_a_safe_sink_reset_n),
    .auto_dmiXing_in_d_mem_0_opcode        (_dmInner_auto_dmiXing_in_d_mem_0_opcode),
    .auto_dmiXing_in_d_mem_0_size          (_dmInner_auto_dmiXing_in_d_mem_0_size),
    .auto_dmiXing_in_d_mem_0_source        (_dmInner_auto_dmiXing_in_d_mem_0_source),
    .auto_dmiXing_in_d_mem_0_data          (_dmInner_auto_dmiXing_in_d_mem_0_data),
    .auto_dmiXing_in_d_ridx                (_dmOuter_auto_asource_out_d_ridx),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmiXing_in_d_widx                (_dmInner_auto_dmiXing_in_d_widx),
    .auto_dmiXing_in_d_safe_ridx_valid     (_dmOuter_auto_asource_out_d_safe_ridx_valid),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmiXing_in_d_safe_widx_valid     (_dmInner_auto_dmiXing_in_d_safe_widx_valid),
    .auto_dmiXing_in_d_safe_source_reset_n
      (_dmInner_auto_dmiXing_in_d_safe_source_reset_n),
    .auto_dmiXing_in_d_safe_sink_reset_n
      (_dmOuter_auto_asource_out_d_safe_sink_reset_n),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .auto_dmInner_tl_in_a_ready            (auto_dmInner_dmInner_tl_in_a_ready_0),
    .auto_dmInner_tl_in_a_valid            (auto_dmInner_dmInner_tl_in_a_valid_0),
    .auto_dmInner_tl_in_a_bits_opcode      (auto_dmInner_dmInner_tl_in_a_bits_opcode_0),
    .auto_dmInner_tl_in_a_bits_param       (auto_dmInner_dmInner_tl_in_a_bits_param_0),
    .auto_dmInner_tl_in_a_bits_size        (auto_dmInner_dmInner_tl_in_a_bits_size_0),
    .auto_dmInner_tl_in_a_bits_source      (auto_dmInner_dmInner_tl_in_a_bits_source_0),
    .auto_dmInner_tl_in_a_bits_address     (auto_dmInner_dmInner_tl_in_a_bits_address_0),
    .auto_dmInner_tl_in_a_bits_mask        (auto_dmInner_dmInner_tl_in_a_bits_mask_0),
    .auto_dmInner_tl_in_a_bits_data        (auto_dmInner_dmInner_tl_in_a_bits_data_0),
    .auto_dmInner_tl_in_a_bits_corrupt     (auto_dmInner_dmInner_tl_in_a_bits_corrupt_0),
    .auto_dmInner_tl_in_d_ready            (auto_dmInner_dmInner_tl_in_d_ready_0),
    .auto_dmInner_tl_in_d_valid            (auto_dmInner_dmInner_tl_in_d_valid_0),
    .auto_dmInner_tl_in_d_bits_opcode      (auto_dmInner_dmInner_tl_in_d_bits_opcode_0),
    .auto_dmInner_tl_in_d_bits_size        (auto_dmInner_dmInner_tl_in_d_bits_size_0),
    .auto_dmInner_tl_in_d_bits_source      (auto_dmInner_dmInner_tl_in_d_bits_source_0),
    .auto_dmInner_tl_in_d_bits_data        (auto_dmInner_dmInner_tl_in_d_bits_data_0),
    .io_debug_clock                        (io_debug_clock_0),
    .io_debug_reset                        (io_debug_reset_0),
    .io_tl_clock                           (io_tl_clock_0),
    .io_tl_reset                           (io_tl_reset_0),
    .io_dmactive                           (_dmOuter_io_ctrl_dmactive),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_resumereq          (_dmOuter_io_innerCtrl_mem_0_resumereq),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hartsel            (_dmOuter_io_innerCtrl_mem_0_hartsel),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_ackhavereset       (_dmOuter_io_innerCtrl_mem_0_ackhavereset),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hasel              (_dmOuter_io_innerCtrl_mem_0_hasel),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hamask_0           (_dmOuter_io_innerCtrl_mem_0_hamask_0),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hamask_1           (_dmOuter_io_innerCtrl_mem_0_hamask_1),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hamask_2           (_dmOuter_io_innerCtrl_mem_0_hamask_2),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hamask_3           (_dmOuter_io_innerCtrl_mem_0_hamask_3),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hamask_4           (_dmOuter_io_innerCtrl_mem_0_hamask_4),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hamask_5           (_dmOuter_io_innerCtrl_mem_0_hamask_5),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hamask_6           (_dmOuter_io_innerCtrl_mem_0_hamask_6),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hamask_7           (_dmOuter_io_innerCtrl_mem_0_hamask_7),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hrmask_0           (_dmOuter_io_innerCtrl_mem_0_hrmask_0),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hrmask_1           (_dmOuter_io_innerCtrl_mem_0_hrmask_1),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hrmask_2           (_dmOuter_io_innerCtrl_mem_0_hrmask_2),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hrmask_3           (_dmOuter_io_innerCtrl_mem_0_hrmask_3),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hrmask_4           (_dmOuter_io_innerCtrl_mem_0_hrmask_4),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hrmask_5           (_dmOuter_io_innerCtrl_mem_0_hrmask_5),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hrmask_6           (_dmOuter_io_innerCtrl_mem_0_hrmask_6),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_mem_0_hrmask_7           (_dmOuter_io_innerCtrl_mem_0_hrmask_7),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_ridx                     (_dmInner_io_innerCtrl_ridx),
    .io_innerCtrl_widx                     (_dmOuter_io_innerCtrl_widx),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_safe_ridx_valid          (_dmInner_io_innerCtrl_safe_ridx_valid),
    .io_innerCtrl_safe_widx_valid          (_dmOuter_io_innerCtrl_safe_widx_valid),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_safe_source_reset_n      (_dmOuter_io_innerCtrl_safe_source_reset_n),	// src/main/scala/devices/debug/Debug.scala:1941:53
    .io_innerCtrl_safe_sink_reset_n        (_dmInner_io_innerCtrl_safe_sink_reset_n),
    .io_hgDebugInt_0                       (_dmInner_io_hgDebugInt_0),
    .io_hgDebugInt_1                       (_dmInner_io_hgDebugInt_1),
    .io_hgDebugInt_2                       (_dmInner_io_hgDebugInt_2),
    .io_hgDebugInt_3                       (_dmInner_io_hgDebugInt_3),
    .io_hgDebugInt_4                       (_dmInner_io_hgDebugInt_4),
    .io_hgDebugInt_5                       (_dmInner_io_hgDebugInt_5),
    .io_hgDebugInt_6                       (_dmInner_io_hgDebugInt_6),
    .io_hgDebugInt_7                       (_dmInner_io_hgDebugInt_7),
    .io_hartIsInReset_0                    (io_hartIsInReset_0_0),
    .io_hartIsInReset_1                    (io_hartIsInReset_1_0),
    .io_hartIsInReset_2                    (io_hartIsInReset_2_0),
    .io_hartIsInReset_3                    (io_hartIsInReset_3_0),
    .io_hartIsInReset_4                    (io_hartIsInReset_4_0),
    .io_hartIsInReset_5                    (io_hartIsInReset_5_0),
    .io_hartIsInReset_6                    (io_hartIsInReset_6_0),
    .io_hartIsInReset_7                    (io_hartIsInReset_7_0)
  );	// src/main/scala/devices/debug/Debug.scala:1942:53
  assign auto_dmInner_dmInner_tl_in_a_ready = auto_dmInner_dmInner_tl_in_a_ready_0;
  assign auto_dmInner_dmInner_tl_in_d_valid = auto_dmInner_dmInner_tl_in_d_valid_0;
  assign auto_dmInner_dmInner_tl_in_d_bits_opcode =
    auto_dmInner_dmInner_tl_in_d_bits_opcode_0;
  assign auto_dmInner_dmInner_tl_in_d_bits_size =
    auto_dmInner_dmInner_tl_in_d_bits_size_0;
  assign auto_dmInner_dmInner_tl_in_d_bits_source =
    auto_dmInner_dmInner_tl_in_d_bits_source_0;
  assign auto_dmInner_dmInner_tl_in_d_bits_data =
    auto_dmInner_dmInner_tl_in_d_bits_data_0;
  assign auto_dmOuter_intsource_out_7_sync_0 = auto_dmOuter_intsource_out_7_sync_0_0;
  assign auto_dmOuter_intsource_out_6_sync_0 = auto_dmOuter_intsource_out_6_sync_0_0;
  assign auto_dmOuter_intsource_out_5_sync_0 = auto_dmOuter_intsource_out_5_sync_0_0;
  assign auto_dmOuter_intsource_out_4_sync_0 = auto_dmOuter_intsource_out_4_sync_0_0;
  assign auto_dmOuter_intsource_out_3_sync_0 = auto_dmOuter_intsource_out_3_sync_0_0;
  assign auto_dmOuter_intsource_out_2_sync_0 = auto_dmOuter_intsource_out_2_sync_0_0;
  assign auto_dmOuter_intsource_out_1_sync_0 = auto_dmOuter_intsource_out_1_sync_0_0;
  assign auto_dmOuter_intsource_out_0_sync_0 = auto_dmOuter_intsource_out_0_sync_0_0;
  assign io_ctrl_ndreset = io_ctrl_ndreset_0;
  assign io_ctrl_dmactive = io_ctrl_dmactive_0;
  assign io_dmi_dmi_req_ready = io_dmi_dmi_req_ready_0;
  assign io_dmi_dmi_resp_valid = io_dmi_dmi_resp_valid_0;
  assign io_dmi_dmi_resp_bits_data = io_dmi_dmi_resp_bits_data_0;
  assign io_dmi_dmi_resp_bits_resp = io_dmi_dmi_resp_bits_resp_0;
endmodule

